[Пнд, 21 Окт 2013 13:52:18 virt-install 2452] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -n Client -r 4096 -f /var/lib/xen/images/Client.img --vnc -- location=http://mi.mirror.garr.it/mirrors/ubuntu/dists/precise/main/installer-amd64/20101020ubuntu134/images/netboot/xen
[Пнд, 21 Окт 2013 13:52:18 virt-install 2452] ERROR (cli:444) Unknown argument 'location=http://mi.mirror.garr.it/mirrors/ubuntu/dists/precise/main/installer-amd64/20101020ubuntu134/images/netboot/xen'
[Пнд, 21 Окт 2013 13:53:15 virt-install 2453] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -n Client -r 4096 -f /var/lib/xen/images/Client.img
[Пнд, 21 Окт 2013 13:53:15 virt-install 2453] DEBUG (cli:331) Requesting libvirt URI default
[Пнд, 21 Окт 2013 13:53:15 virt-install 2453] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Пнд, 21 Окт 2013 13:53:15 virt-install 2453] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Пнд, 21 Окт 2013 14:55:40 virt-install 10153] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -n Client -r 4096 -f /var/lib/xen/images/Client.img --vnc -- location=http://mi.mirror.garr.it/mirrors/ubuntu/dists/precise/main/installer-amd64/20101020ubuntu134/images/netboot/xen
[Пнд, 21 Окт 2013 14:55:40 virt-install 10153] ERROR (cli:444) Unknown argument 'location=http://mi.mirror.garr.it/mirrors/ubuntu/dists/precise/main/installer-amd64/20101020ubuntu134/images/netboot/xen'
[Пнд, 21 Окт 2013 14:57:33 virt-install 10158] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -n Client -r 4096 -f /var/lib/xen/images/Client.img --vnc -- location=http://mi.mirror.garr.it/mirrors/CentOS/6.4/os/x86_64
[Пнд, 21 Окт 2013 14:57:33 virt-install 10158] ERROR (cli:444) Unknown argument 'location=http://mi.mirror.garr.it/mirrors/CentOS/6.4/os/x86_64'
[Пнд, 21 Окт 2013 14:57:56 virt-install 10159] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -n Client -r 4096 -f /var/lib/xen/images/Client.img
[Пнд, 21 Окт 2013 14:57:56 virt-install 10159] DEBUG (cli:331) Requesting libvirt URI default
[Пнд, 21 Окт 2013 14:57:56 virt-install 10159] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Пнд, 21 Окт 2013 14:57:56 virt-install 10159] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 13:42:36 virt-install 24980] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 --accelerate -n Ubuntu  -f /path/to/client.img  -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 13:42:36 virt-install 24980] ERROR (cli:444) Unknown argument ' -f'
[Вто, 22 Окт 2013 13:45:46 virt-install 24999] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 --accelerate -n Ubuntu  -f /dev/Grid-vg/client  -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 13:45:46 virt-install 24999] ERROR (cli:444) Unknown argument ' -f'
[Вто, 22 Окт 2013 13:48:14 virt-install 25012] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 --accelerate -n client -f /var/lib/libvirt/images/client.img -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 13:48:14 virt-install 25012] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 13:48:14 virt-install 25012] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 13:48:14 virt-install 25012] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 13:56:07 virt-install 25033] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 --accelerate -n client -f /var/lib/libvirt/images/client.img -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 13:56:07 virt-install 25033] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 13:56:07 virt-install 25033] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 13:56:07 virt-install 25033] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:01:51 virt-install 25059] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 --accelerate -n client -f /var/lib/libvirt/images/client.img -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 14:01:51 virt-install 25059] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 14:01:51 virt-install 25059] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:01:51 virt-install 25059] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:02:22 virt-install 25060] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 -n client -f /var/lib/libvirt/images/client.img -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 14:02:22 virt-install 25060] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 14:02:22 virt-install 25060] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:02:22 virt-install 25060] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:06:06 virt-install 25078] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 4096 -n client -f /var/lib/libvirt/images/client.img -l http://ua.archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/
[Вто, 22 Окт 2013 14:06:06 virt-install 25078] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 14:06:06 virt-install 25078] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:06:06 virt-install 25078] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:10:30 virt-install 25083] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install --ram 4096 --name client --disk /dev/Grid-vg/client -l http://ua.archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/
[Вто, 22 Окт 2013 14:10:30 virt-install 25083] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 14:10:30 virt-install 25083] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:10:30 virt-install 25083] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:29:54 virt-install 25786] DEBUG (cli:226) Launched with command line:
/usr/bin/virt-install -r 1024 -n client -f /var/lib/libvirt/images/client.img -l http://ftp.ubuntu.com/ubuntu/dists/maverick/main/installer-amd64/
[Вто, 22 Окт 2013 14:29:54 virt-install 25786] DEBUG (cli:331) Requesting libvirt URI default
[Вто, 22 Окт 2013 14:29:54 virt-install 25786] ERROR (cli:444) unable to connect to 'localhost:8000': Connection refused
[Вто, 22 Окт 2013 14:29:54 virt-install 25786] DEBUG (cli:447) 
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 1017, in <module>
    sys.exit(main())
  File "/usr/bin/virt-install", line 997, in main
    conn = cli.getConnection(options.connect)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 332, in getConnection
    conn = open_connection(uri)
  File "/usr/lib/python2.7/dist-packages/virtinst/cli.py", line 347, in open_connection
    open_flags)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirtError: unable to connect to 'localhost:8000': Connection refused
